on:
  pull_request:
    branches:
      - develop

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ">=24"

      - run: npm i -g --force corepack@latest && corepack enable

      - name: "Install dependencies"
        run: npx nypm@latest i

      - name: Install Nuxt
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
